name: CI/CD for LoginApi to Ubuntu EC2

on:
  push:
    branches: [ main ]

jobs:
  deploy-loginapi:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '8.0.x'

      - name: Restore packages
        run: dotnet restore LoginApi.csproj

      - name: Build project
        run: dotnet build LoginApi.csproj --configuration Release

      - name: Publish project
        run: dotnet publish LoginApi.csproj -c Release -o ./publish

      - name: Zip published output
        run: zip -r loginapi.zip ./publish

      - name: Upload zip to EC2
        uses: appleboy/scp-action@v0.1.4
        with:
          host: ${{ vars.EC2_HOST }}
          username: ${{ vars.EC2_USER }}
          key: ${{ secrets.EC2_SSH_KEY }}
          source: "loginapi.zip"
          target: "/home/${{ vars.EC2_USER }}/deploy"

      - name: SSH and deploy to EC2
        uses: appleboy/ssh-action@v0.1.10
        with:
          host: ${{ vars.EC2_HOST }}
          username: ${{ vars.EC2_USER }}
          key: ${{ secrets.EC2_SSH_KEY }}
          script: |
            # ───── Install .NET Runtime ─────
            wget https://dot.net/v1/dotnet-install.sh
            chmod +x dotnet-install.sh
            ./dotnet-install.sh --runtime aspnetcore --version 8.0
            export DOTNET_ROOT=$HOME/.dotnet
            export PATH=$PATH:$DOTNET_ROOT:$DOTNET_ROOT/tools

            # ───── Install PostgreSQL ─────
            sudo apt-get update
            sudo apt-get install -y postgresql postgresql-contrib
            sudo systemctl enable postgresql
            sudo systemctl start postgresql

            # ───── Create PostgreSQL User & DB (if needed) ─────
            sudo -u postgres psql -c "CREATE USER loginuser WITH PASSWORD 'admin123';"
            sudo -u postgres psql -c "CREATE DATABASE logindb OWNER loginuser;"

            # ───── Prepare Deployment Directory ─────
            sudo mkdir -p /var/www/loginapi
            sudo unzip -o /home/${{ vars.EC2_USER }}/deploy/loginapi.zip -d /var/www/loginapi
            sudo chown -R www-data:www-data /var/www/loginapi

            # ───── Create kestrel-loginapi.service if Missing ─────
            SERVICE_PATH="/etc/systemd/system/kestrel-loginapi.service"
            if [ ! -f "$SERVICE_PATH" ]; then
              sudo tee "$SERVICE_PATH" > /dev/null << 'EOF'
              
             [Unit]
             Description=LoginApi .NET Web App

             [Service]
             WorkingDirectory=/var/www/loginapi
             ExecStart=/usr/bin/dotnet /var/www/loginapi/LoginApi.dll
             Restart=always
             RestartSec=10
             KillSignal=SIGINT
             SyslogIdentifier=loginapi
             User=www-data
             Environment=ASPNETCORE_ENVIRONMENT=Production

             [Install]
             WantedBy=multi-user.target
             EOF
              sudo systemctl daemon-reload
              sudo systemctl enable kestrel-loginapi.service
             fi

             # ───── Restart the Service ─────
             sudo systemctl restart kestrel-loginapi.service
