name: CI/CD for LoginApi to Ubuntu EC2

on:
  push:
    branches: [ main ]

jobs:
  deploy-loginapi:
    runs-on: ubuntu-latest

    steps:
      # ───── Checkout Code ─────
      - name: Checkout repository
        uses: actions/checkout@v3

      # ───── Setup .NET SDK ─────
      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '8.0.x'

      # ───── Restore Dependencies ─────
      - name: Restore packages
        run: dotnet restore LoginApi.csproj

      # ───── Build Project ─────
      - name: Build project
        run: dotnet build LoginApi.csproj --configuration Release

      # ───── Publish Project ─────
      - name: Publish project
        run: dotnet publish LoginApi.csproj -c Release -o ./publish

      # ───── Compress Published Files ─────
      - name: Zip published output
        run: zip -r loginapi.zip ./publish

      # ───── Upload to EC2 ─────
      - name: Upload zip to EC2
        uses: appleboy/scp-action@v0.1.4
        with:
          host: ${{ vars.EC2_HOST }}
          username: ${{ vars.EC2_USER }}
          key: ${{ secrets.EC2_SSH_KEY }}
          source: "loginapi.zip"
          target: "/home/${{ vars.EC2_USER }}/deploy"

      # ───── SSH into EC2 and Deploy ─────
      - name: SSH and deploy to EC2
        uses: appleboy/ssh-action@v0.1.10
        with:
          host: ${{ vars.EC2_HOST }}
          username: ${{ vars.EC2_USER }}
          key: ${{ secrets.EC2_SSH_KEY }}
          script: |
            unzip -o /home/${{ vars.EC2_USER }}/deploy/loginapi.zip -d /var/www/loginapi
            cd /var/www/loginapi
            dotnet LoginApi.dll
            sudo systemctl restart kestrel-loginapi.service || true
