    # ───── SSH into EC2 and Deploy ─────
    - name: SSH and deploy to EC2
      uses: appleboy/ssh-action@v0.1.10
      with:
        host: ${{ vars.EC2_HOST }}
        username: ${{ vars.EC2_USER }}
        key: ${{ secrets.EC2_SSH_KEY }}
        script: |
          # ───── Install PostgreSQL ─────
          sudo apt update
          sudo apt install -y postgresql postgresql-contrib

          # ───── Start PostgreSQL ─────
          sudo systemctl enable postgresql
          sudo systemctl start postgresql

          # ───── Create Role if Not Exists ─────
          sudo -u postgres psql -c "DO \$\$ BEGIN IF NOT EXISTS (SELECT FROM pg_catalog.pg_roles WHERE rolname = 'login_user') THEN CREATE ROLE login_user WITH LOGIN PASSWORD 'secure_password'; END IF; END \$\$;"

          # ───── Create Database if Not Exists ─────
          DB_EXISTS=$(sudo -u postgres psql -tAc "SELECT 1 FROM pg_database WHERE datname='login_db'")
          if [ "$DB_EXISTS" != "1" ]; then
            sudo -u postgres createdb -O login_user login_db
          fi

          # ───── Ensure Deployment Directory Exists ─────
          sudo mkdir -p /var/www/loginapi
          sudo chown $USER:$USER /var/www/loginapi

          # ───── Unzip and Deploy ─────
          unzip -o /home/${{ vars.EC2_USER }}/deploy/loginapi.zip -d /var/www/loginapi

          # ───── Apply EF Core Migrations ─────
          cd /var/www/loginapi
          dotnet LoginApi.dll --apply-migrations

          # ───── Restart Backend Service ─────
          sudo systemctl restart kestrel-loginapi.service
