name: CI/CD for LoginApi to Ubuntu EC2

on:
  push:
    branches: [ main ]
jobs:
  deploy-loginapi:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '8.0.x'

      - name: Restore packages
        run: dotnet restore LoginApi.csproj

      - name: Build project
        run: dotnet build LoginApi.csproj --configuration Release

      - name: Publish project
        run: dotnet publish LoginApi.csproj -c Release -o ./publish

      - name: Zip published output
        run: zip -r loginapi.zip ./publish

      - name: Upload zip to EC2
        uses: appleboy/scp-action@v0.1.4
        with:
          host: ${{ vars.EC2_HOST }}
          username: ${{ vars.EC2_USER }}
          key: ${{ secrets.EC2_SSH_KEY }}
          source: "loginapi.zip"
          target: "/home/${{ vars.EC2_USER }}/deploy"
          
       - name: Ensure deployment directory and dotnet installed
        run: |
        ssh <user>@<host> 'mkdir -p /var/www/loginapi'
        ssh <user>@<host> 'which dotnet || (wget https://dot.net/v1/dotnet-install.sh -O dotnet-install.sh && bash dotnet-install.sh --channel 8.0)'
     
      - name: SSH and deploy to EC2
        uses: appleboy/ssh-action@v0.1.10
        with:
          host: ${{ vars.EC2_HOST }}
          username: ${{ vars.EC2_USER }}
          key: ${{ secrets.EC2_SSH_KEY }}
          script: |
            unzip -o /home/${{ vars.EC2_USER }}/deploy/loginapi.zip -d /var/www/loginapi
            cd /var/www/loginapi
            dotnet LoginApi.dll
